name = "SimpleEvolve"
uuid = "6d5e804b-4f14-450a-9571-280c5529278f"
authors = ["Nick and Arnab"]
version = "1.0.0-DEV"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
DSP = "0.8.3"
DifferentialEquations = "7.16.1"
FFTW = "1.8.1"
ForwardDiff = "0.10.38"
LineSearches = "7.3.0"
LinearAlgebra = "1.11.0"
NPZ = "0.4.3"
Optim = "1.12.0"
Plots = "1.40.11"
Polynomials = "4.0.19"
Random = "1.11.0"
ReverseDiff = "1.16.1"
SciMLSensitivity = "7.76.0"
SpecialFunctions = "2.5.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
